### ISSUE TITLE
Peer dependency change

### ISSUE THREAD

**Issue by HarelM** [ZeevKatz/ngx-d3#15]
Is it possible to remove/update the peer dependency of angular core?

**Comment by ZeevKatz** [comment]
Sure!

**Comment by HarelM** [comment]
Thanks for the super quick response! :-)
I'm currently upgrading my code from angular 8 to 9 or later (hopefully).
If I encounter issues I'll be reporting them although I don't see a reason I should find any issues as this library is a simple wrapper around d3 and I don't think it should break due to angular upgrades...

**Comment by ZeevKatz** [comment]
I don't see any issue with this upgrade either.
I'll push the changes ASAP.

**Comment by ZeevKatz** [comment]
@HarelM Done! You can upgrade to `0.3.0` 🎊

**Comment by HarelM** [comment]
Thanks mate!!
I appreciate it :-)
