### ISSUE TITLE
Support Angular 12

### ISSUE THREAD

**Issue by Feasoron** [ZeevKatz/ngx-d3#18]
We have an application using this library that has been upgraded to Angular 12. I've done a bit of testing and ngx-d3 runs fine, but it requires use to run and npm install --force to get past the fact that the dependencies in the package.json is pinned at ^10.2.4.

**Comment by ZeevKatz** [comment]
@Feasoron Thanks for reporting, working on it - https://github.com/ZeevKatz/ngx-d3/pull/19

**Comment by ZeevKatz** [comment]
Close this issue after upgrading to Angular 12.
https://www.npmjs.com/package/@katze/ngx-d3/v/1.0.0
