### ISSUE TITLE
Doc: incorrect installation instruction

### ISSUE THREAD

**Issue by dimitri-bret** [ZeevKatz/ngx-d3#7]
### Doc error
Writting ```yarn install @katze/ngx-d3``` shall be replaced by ``` yarn add @katze/ngx-d3``` as the ```install``` command has been replace with ```add```  to add new dependencies

**Comment by ZeevKatz** [comment]
@DimitriBret I already saw your PR for this issue and I asked for changes before we will rebase it onto `develop` and publish a new release. 
Thanks for your attention and contribution! 👏
